### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by hessijames79** [sw-home/FHEM-HomeConnect#2]
Good afternoon!

The HomeConnect module causes regular freezes in my setup, e. g.:
freezemon s:00:07:08 e:00:07:09 f:1.717 d:tmr-HomeConnect_Timer(EG.KU.Backofen)

freezemon s:03:12:39 e:03:12:43 f:4.697 d:cmd-set EG.KU.Geschirrspueler init(N/A) cmd-set EG.KU.Backofen init(N/A) cmd-set EG.KU.Kochfeld init(N/A) fn-SetFn(EG.KU.Geschirrspueler) fn-SetFn(EG.KU.Backofen) fn-SetFn(EG.KU.Kochfeld) tmr-HomeConnectConnection_RefreshTokenTimer(homeconnect)

Patrick

**Comment by hessijames79** [comment]
Any news on this? Just got a 180s (!) freeze.

**Comment by sw-home** [comment]
Hi hessljames, refreshing the token is indeed using a blocking get. Since it happens only about once a day I dont think the extra work and code compexity to use a non blocking get here would be justified. You are however encouraged to submit a pull request if you have a better solution.
(p.s. sorry for the delayed answer, I didnt monitor the github issues, only the FHEM forum)

**Comment by hessijames79** [comment]
I hope there is a misunderstanding here. A 180s freeze for the whole fhem instance is neither a minor issue nor a case for "won't fix". In addition, slightly increased code complexity is a very small price for a stable system.

Concerning the bug: As you apparently missed in my report, HomeConnectConnection_RefreshTokenTimer() is not the only source of freezes.

**Comment by marvin78** [comment]
> I hope there is a misunderstanding here. A 180s freeze for the whole fhem instance is neither a minor issue nor a case for "won't fix". In addition, slightly increased code complexity is a very small price for a stable system.

I completely agree.
